# Generated by Django 3.0.6 on 2020-07-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jrsuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
