# Generated by Django 3.0.6 on 2020-07-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200715_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=40)),
                ('rank', models.IntegerField()),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('jobType', models.CharField(max_length=15)),
                ('salary', models.CharField(max_length=15)),
                ('jobDescription', models.CharField(max_length=800)),
            ],
        ),
    ]
