# Generated by Django 3.0.6 on 2020-07-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_companies_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='rank',
            field=models.FloatField(),
        ),
    ]
