# Generated by Django 3.0.6 on 2020-07-16 09:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200715_1947'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jrsuser',
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='jrsuser',
            name='id',
        ),
        migrations.AddField(
            model_name='job',
            name='postedby',
            field=models.CharField(default='Sharon', max_length=20),
        ),
        migrations.AlterField(
            model_name='jrsuser',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
