# Generated by Django 3.0.6 on 2020-07-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200716_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jrsuser',
            name='password',
        ),
    ]
