# Generated by Django 3.0.6 on 2020-07-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_jrsuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='logo',
        ),
    ]
