# Generated by Django 3.0.6 on 2020-07-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200717_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mustmeet1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='mustmeet2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='mustmeet3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='mustmeet4',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='mustmeet5',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='mustmeet6',
            field=models.CharField(default='', max_length=30),
        ),
    ]
