# Generated by Django 3.0.6 on 2020-07-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200718_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='logo',
        ),
        migrations.AddField(
            model_name='companies',
            name='logo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
