# Generated by Django 3.0.6 on 2020-07-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20200718_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='logo',
            field=models.ImageField(upload_to='static/mainapp/assets/images'),
        ),
    ]
